package com.tinkoffsirius.koshelok

enum class Icons(val id: Int, val drawableId: Int) {
    CLOTHES(0, R.drawable.ic_clothes),
    PRESENT(1, R.drawable.ic_present),
    FOOD(2, R.drawable.ic_food),
    SALARY(3, R.drawable.ic_salary),
    SPORT(4, R.drawable.ic_sport),
    CAPITALIZE(5, R.drawable.ic_capitalize),
    BOX(6 , R.drawable.ic_box),
    BUILD(7, R.drawable.ic_build),
    BALL(8, R.drawable.ic_ball),
    BASKET(9 , R.drawable.ic_busket),
    CUP(10, R.drawable.ic_cup),
    CAR(11 , R.drawable.ic_car),
    CINEMA(12 , R.drawable.ic_cinima),
    DIAMOND(13, R.drawable.ic_dimond),
    EDUCATION(14 , R.drawable.ic_education),
    ETHERNET(15 , R.drawable.ic_ethernet),
    FRIEND(16 , R.drawable.ic_friend),
    HOSPITAL(17 , R.drawable.ic_hospital),
    INFORMATION(18 , R.drawable.ic_information),
    MASK(19 , R.drawable.ic_mask),
    MEDICINE(20 , R.drawable.ic_medicine),
    MUSIC(21 , R.drawable.ic_music),
    PET(22 , R.drawable.ic_pet),
    PHONE(23 , R.drawable.ic_phone),
    PLANE(24 , R.drawable.ic_plane),
    SEA(25, R.drawable.ic_sea),
    TRAIN(26, R.drawable.ic_train),
    TV(27, R.drawable.ic_tv),
    WALLET(28 , R.drawable.ic_wallet),
    ANOTHER(29 , R.drawable.ic_another)
}
